version: '3.1'

services:
  app:
    image: 'sha256:107eb046189d269ec768a498dd11ef958fd93333b4665e3aa0ba212dd57a4dd2'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
        - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234


